Update publish_alpha.yml

diff --git a/.github/workflows/publish_alpha.yml b/.github/workflows/publish_alpha.yml
--- a/.github/workflows/publish_alpha.yml
+++ b/.github/workflows/publish_alpha.yml
@@ -53,7 +53,7 @@ jobs:
 
       - name: Build Alpha APK
         id: build_alpha
-        run: ./gradlew assembleAlphaRelease
+        run: ./gradlew assembleAlphaRelease || { echo 'Build failed'; exit 1; }
 
       - name: Sign Alpha APK
         if: success()
