Update publish_alpha.yml

diff --git a/.github/workflows/publish_alpha.yml b/.github/workflows/publish_alpha.yml
--- a/.github/workflows/publish_alpha.yml
+++ b/.github/workflows/publish_alpha.yml
@@ -109,15 +109,24 @@ jobs:
           COMMIT_LOG=$(cat commit_log.txt)
           MESSAGE="<b>New Awery Alpha Update</b>%0A%0A<b>Latest Changes:</b>%0A${COMMIT_LOG}"
           MESSAGE="${MESSAGE:0:1020}"
+    
+          echo "COMMIT_LOG: $COMMIT_LOG"
+          echo "MESSAGE: $MESSAGE"
+
+          if [ ! -f "app/build/outputs/apk/alpha/release/app-alpha-release-signed.apk" ]; then
+          echo "Error: APK file not found."
+          exit 1
+          fi
+
           echo "Sending to Telegram..."
           curl -v -X POST \
-            "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument" \
-            -F "chat_id=-1002066701332" \
-            -F "document=@app/build/outputs/apk/alpha/release/app-alpha-release-signed.apk" \
-            -F "caption=$MESSAGE" \
-            -F "parse_mode=HTML" \
-            -F "disable_web_page_preview=true" \
-            -F "message_thread_id=28"
+          "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument" \
+          -F "chat_id=-1002066701332" \
+          -F "document=@app/build/outputs/apk/alpha/release/app-alpha-release-signed.apk" \
+          -F "caption=$MESSAGE" \
+          -F "parse_mode=HTML" \
+          -F "disable_web_page_preview=true" \
+          -F "message_thread_id=28"
 
       - name: Send to Discord
         if: success()
